#include "menuinterface.h"
#include <iostream>
//#include "asset.h"
//#include <string>
#include "date.h"
//#include "television.h"
#include "testingsetting.h"
#include <iomanip>

/* ------------------------------------------------------------------------------
 * DO NOT edit this file, your code will be tested against an un modified version
 * Enable testing mode and set options in the testingsetting.h file.
 * -----------------------------------------------------------------------------*/

#if TESTING
#include "assettesting.h"
#include <iomanip>

/**
 * @brief main run testing code.
 * @return
 */
int main() {
  AssetTesting test;
  test.initialize();
  std::cout << std::left << std::setw(30) << "Date class tests ... " << test.testDate()
            << std::endl;
  std::cout << std::setw(30) << "Asset class tests ... " << test.testAsset() << std::endl;
  std::cout << std::setw(30) << "Custodian class tests ... " << test.testCustodian() << std::endl;
  std::cout << std::setw(30) << "Computer class tests ... " << test.testComputer() << std::endl;
  std::cout << std::setw(30) << "Phone class tests ... " << test.testPhone() << std::endl;
  std::cout << std::setw(30) << "Television class tests ... " << test.testTelevision() << std::endl;
  std::cout << std::setw(30) << "HMD class tests ... " << test.testHMD() << std::endl;
  test.printFailures(std::cout);
  return 0;
}
#else

/**
 * @brief main simple main function runs the MenuInterface until quit.
 * @return
 */
int main() {
  MenuInterface m{std::cout, std::cin};
  m.displayMainMenu();
  while (m.processSelection(m.getCharacterInput())) {
    m.displayMainMenu();
  }
  return 0;
}



#endif
